language: julia
os:
  - linux
julia:
  - 1.3
notifications:
  email: false
jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      env:
        - PYTHON=python3
      addons:
        apt:
          packages:
            - qt5-default
            # pgfplots
            - pdf2svg
            - texlive-latex-base
            - texlive-binaries
            - texlive-pictures
            - texlive-latex-extra
            - texlive-luatex
            - ghostscript-x
            # orca
            - libgconf2-4
            # pyplot
            - python3-matplotlib
      script:
        - xvfb-run julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - travis_wait 30 xvfb-run julia --project=docs/ docs/make.jl
      after_success: skip
